# Generated by Django 5.1.7 on 2025-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb_image', models.ImageField(upload_to='rgb_images/')),
                ('ir_image', models.ImageField(upload_to='ir_images/')),
            ],
        ),
    ]
